kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: kainvey/zeppelin:v1.9
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
